version: '3'

services:
  portainer:
    container_name: ${CONTAINER_NAME:-portainer}
    restart: unless-stopped
    image: portainer/portainer-ce
    volumes:
      - ${PORTAINER_DATA_PATH:-./data}:/data
      - ${PORTAINER_SSL_PATH:-./certs}:/certs
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - ${PORT_HOST:-443}:${PORT_CONTAINER:-9443}
    env_file:
      - ./.env
    environment:
      VIRTUAL_HOST: $DOMAINS
      LETSENCRYPT_HOST: $DOMAINS
      LETSENCRYPT_EMAIL: $LETSENCRYPT_EMAIL
      SSL:
      SSLCERT: /certs/$MAIN_DOMAIN.crt
      SSLKEY: /certs/$MAIN_DOMAIN.key
    command: --admin-password $ENCRYPTED_PASSWORD

networks:
  portainer_network:
    name: ${NETWORK:-portainer_network}
